/* tslint:disable */
/* eslint-disable */
/**
 * Feryv OAuth
 * Feryv OAuth Server API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    RefreshResponse,
    RefreshResponseFromJSON,
    RefreshResponseToJSON,
} from '../models';

export interface RefreshRequest {
    feryvrefreshtoken?: string | null;
    feryvcsrftoken?: string | null;
}

/**
 * 
 */
export class AuthenticateApi extends runtime.BaseAPI {

    /**
     * Refreshes the users access token.
     */
    async refreshRaw(requestParameters: RefreshRequest): Promise<runtime.ApiResponse<RefreshResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.feryvrefreshtoken !== undefined && requestParameters.feryvrefreshtoken !== null) {
            headerParameters['Feryvrefreshtoken'] = String(requestParameters.feryvrefreshtoken);
        }

        if (requestParameters.feryvcsrftoken !== undefined && requestParameters.feryvcsrftoken !== null) {
            headerParameters['Feryvcsrftoken'] = String(requestParameters.feryvcsrftoken);
        }

        const response = await this.request({
            path: `/api/refresh`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => RefreshResponseFromJSON(jsonValue));
    }

    /**
     * Refreshes the users access token.
     */
    async refresh(requestParameters: RefreshRequest): Promise<RefreshResponse> {
        const response = await this.refreshRaw(requestParameters);
        return await response.value();
    }

}
