/* tslint:disable */
/* eslint-disable */
/**
 * Feryv OAuth
 * Feryv OAuth Server API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    LogoutResponse,
    LogoutResponseFromJSON,
    LogoutResponseToJSON,
    RefreshResponse,
    RefreshResponseFromJSON,
    RefreshResponseToJSON,
} from '../models';

export interface RefreshRequest {
    feryvcsrftoken?: string | null;
    feryvrefreshtoken?: string | null;
}

/**
 * 
 */
export class AuthenticateApi extends runtime.BaseAPI {

    /**
     * Logs the user out.
     */
    async logoutRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<LogoutResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/logout`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LogoutResponseFromJSON(jsonValue));
    }

    /**
     * Logs the user out.
     */
    async logout(initOverrides?: RequestInit): Promise<LogoutResponse> {
        const response = await this.logoutRaw(initOverrides);
        return await response.value();
    }

    /**
     * Refreshes the users access token.
     */
    async refreshRaw(requestParameters: RefreshRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<RefreshResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.feryvcsrftoken !== undefined && requestParameters.feryvcsrftoken !== null) {
            headerParameters['Feryvcsrftoken'] = String(requestParameters.feryvcsrftoken);
        }

        if (requestParameters.feryvrefreshtoken !== undefined && requestParameters.feryvrefreshtoken !== null) {
            headerParameters['Feryvrefreshtoken'] = String(requestParameters.feryvrefreshtoken);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/refresh`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RefreshResponseFromJSON(jsonValue));
    }

    /**
     * Refreshes the users access token.
     */
    async refresh(requestParameters: RefreshRequest, initOverrides?: RequestInit): Promise<RefreshResponse> {
        const response = await this.refreshRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
