definitions:
  LogoutResponse:
    properties:
      msg:
        default: ''
        type: string
        x-nullable: true
    type: object
  RefreshResponse:
    properties:
      accessToken:
        default: ''
        type: string
      msg:
        default: ''
        type: string
        x-nullable: true
    type: object
host: \
info:
  description: Feryv OAuth Server API documentation
  title: Feryv OAuth
  version: 1.0.0
paths:
  /api/logout:
    get:
      description: Logs the user out.
      operationId: logout
      parameters: []
      responses:
        default:
          description: The status of the user logging out.
          schema:
            $ref: '#/definitions/LogoutResponse'
      security:
      - Bearer: []
      tags:
      - Authenticate
  /api/refresh:
    get:
      description: Refreshes the users access token.
      operationId: refresh
      parameters:
      - default: null
        in: header
        name: Feryvcsrftoken
        required: false
        type: string
        x-nullable: true
      - default: null
        in: header
        name: Feryvrefreshtoken
        required: false
        type: string
        x-nullable: true
      responses:
        default:
          description: The status of the refresh attempt, an access token to use for
            protected routes.
          schema:
            $ref: '#/definitions/RefreshResponse'
      security:
      - Refresh_Token_Cookie: []
      - CSRF_Refresh: []
      - Bearer: []
      tags:
      - Authenticate
schemes:
- http
- https
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
  CSRF_Refresh:
    in: cookie
    name: Feryvcsrftoken
    type: apiKey
  Refresh_Token_Cookie:
    in: cookie
    name: Feryvrefreshtoken
    type: apiKey
swagger: '2.0'
